### PR TITLE
Project delivery #1;

### PR DESCRIPTION
**Pull request by ribeirojose**
What we did: 
- Set up architecture so that all pages are translatable;
- Top menu with mock items, language selection, and social network links;
- Added the possibility to add multiple text/image sections using a param to change image sides;
- Add Mailchimp newsletter subscribe modal and nonintrusive toast warning;
- Adjustments to CSS requested by Mathijs.

What we also took the liberty of doing:
- A team page section;
- Add a footer.

### CODE REVIEW

**Comment by dokterbob** [comment]
Good work! Looks much, much better. We're nearly there!

Specifically, the colour and with look really nice. The mailinglist notification is also ++

Few things that need to be done:

- [ ] Footer: CC-NC-BY logo: `<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons-Licentie</a>` instead of reserving rights.
- [ ] Footer: text and entire footer should be less prominent (smaller) as in [NowUI Landing page](https://demos.creative-tim.com/now-ui-kit/examples/landing-page.html)
- [ ] Menu bar: much, much better. Still, the height is significantly more than in the NowUI landing page. If there is no particular reason for this, please make sure it has the same height.
- [ ] Email toaster: great! However, on desktops, there is plenty of space for name/email form elements - so the modal wouldn't be necessary and the design would work better. I really like how it's not obstructive but it makes sure people don't miss out! If you don't want to put more time in this, it's ok as it is.
- [ ] Text template! Big one! We really want to have separate pages, apart from the homepage. Specifically, we need a page with information which we are juridically obliged to provide, which was the main reason for us to prompt the job. This should be the default template, except for the home page. If you run into issues here, 
- [ ] [Homepage template](https://gohugo.io/templates/homepage/): Hugo, by default, allows a different template for the home page. Together with the previous one, this would simplify matters.
- [ ] Both text and homepage templates should have components based on the [headless bundle](https://gohugo.io/content-management/page-bundles/#headless-bundle) template, so components can be added dynamically. Essentially you would have any number of `<menu_item>/<partial.md>` which would define the sections.

**Comment by ribeirojose** [comment]
Thank you for your comments, @dokterbob! Just to give you an update on where we are:

> Good work! Looks much, much better. We're nearly there!
> 
> Specifically, the colour and with look really nice. The mailinglist notification is also ++
> 
> Few things that need to be done:
> 
> * [x]  Footer: CC-NC-BY logo: `<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons-Licentie</a>` instead of reserving rights.
> * [x]  Footer: text and entire footer should be less prominent (smaller) as in [NowUI Landing page](https://demos.creative-tim.com/now-ui-kit/examples/landing-page.html)
> * [x]  Menu bar: much, much better. Still, the height is significantly more than in the NowUI landing page. If there is no particular reason for this, please make sure it has the same height.
> * [x]  Email toaster: great! However, on desktops, there is plenty of space for name/email form elements - so the modal wouldn't be necessary and the design would work better. I really like how it's not obstructive but it makes sure people don't miss out! If you don't want to put more time in this, it's ok as it is.
> * [ ]  Text template! Big one! We really want to have separate pages, apart from the homepage. Specifically, we need a page with information which we are juridically obliged to provide, which was the main reason for us to prompt the job. This should be the default template, except for the home page. If you run into issues here,
> * [ ]  [Homepage template](https://gohugo.io/templates/homepage/): Hugo, by default, allows a different template for the home page. Together with the previous one, this would simplify matters.
> * [ ]  Both text and homepage templates should have components based on the [headless bundle](https://gohugo.io/content-management/page-bundles/#headless-bundle) template, so components can be added dynamically. Essentially you would have any number of `<menu_item>/<partial.md>` which would define the sections.

🔥

**Comment by dokterbob** [comment]
The font of the title changed and I don't think it's an improvement. ssp_temp_capture

**Comment by dokterbob** [comment]
The font of the title changed.

Old: ssp_temp_capture

New: 
ssp_temp_capture

**Comment by dokterbob** [comment]
The search bar stopped being transparent. 
ssp_temp_capture

**Comment by dokterbob** [comment]
Sad to say there's a few issues still:

- [ ] Menu bar became opaque
- [ ] Font of the landing page changed
- [ ] Newsletter model, as well as the menu button for it, got removed. I was actually very happy with that. Please bring it back (in addition to the one you added just now).
- [ ] No footer on landing page.
- [ ] The footer on the next page is actually halfway throughout my browser window on text pages (such as about).
- [ ] MIT is still in the footer, as well as the '2019 Sol Nascente'. Both should go in favor of the single CC logo.
- [ ] The team page doesn't allow adding any text to it.
- [ ] There is still a weird footer page rendered. This should be headless.
- [ ] Proper headless stuff (see below).
- [ ] There's no default text page template, so adding new menu items doesn't work. I suppose it's essentially a matter of changing the about template to the default.

## Headless partials
The idea is to render both the landing page as well as text pages based on multiple (headless) child pages, which are explicitly read from the template. So the `about` page could have several `.md` files in its directory (as well as the `_index.md`), each with its own header, image and content - and they would be automagically read and rendered into one (and only one) document.

For the landing page, these could reside either in the site's root or in a `landing` or `home` folder.

**Comment by dokterbob** [comment]
Looks like it!

Two points, after quick look (so no full review):

1. Why the `headless` subdirectory? I'm pretty sure this site will not have non-headless pages. Also, it should be totally alright to have content in the index as well, that might just be rendered as one of the pages (it's also ok if it's not rendered - if that will lighten your work - just no need to actively exclude it.)
2. There's no need for layouts/templates associated specifically with `about` and `team`. I want to be able to add `banana` section without having to create a template. Note that AFAIK it's perfectly possible to select templates for each subsection in the [frontmatter](https://gohugo.io/content-management/front-matter/).

**Comment by ribeirojose** [comment]
> Looks like it!
> 
> Two points, after quick look (so no full review):
> 
> 1. Why the `headless` subdirectory? I'm pretty sure this site will not have non-headless pages. Also, it should be totally alright to have content in the index as well, that might just be rendered as one of the pages (it's also ok if it's not rendered - if that will lighten your work - just no need to actively exclude it.)

I was just trying to keep things organized. Already put them all in the same directory =) I'm not sure what you meant by "(it's also ok if it's not rendered - if that will lighten your work - just no need to actively exclude it.)"

> 2. There's no need for layouts/templates associated specifically with `about` and `team`. I want to be able to add `banana` section without having to create a template. Note that AFAIK it's perfectly possible to select templates for each subsection in the [frontmatter](https://gohugo.io/content-management/front-matter/).

Also trying to keep things organized. As you can see, there's a 'test' section which doesn't have a referenced layout/template. We just cared to create team layout to keep the team JSON separated. But that was not a requirement, you're free to tell me to erase it =)

**Comment by dokterbob** [comment]
Great steps, again. But again, hate to say there's still a few glitches.

- [ ] Newsletter button in menu bar doesn't have hover and link-type mouse pointer.
- [ ] Pages always display a vertical scroll bar.
- [ ] Social icon links on team page are not circles, they should be exactly as in the Now UI landing page.
- [ ] Index page has different layouts that display differently.
- [ ] The team page doesn't allow textual content. Of course, if we're introducing the members of the team, we would like to say a thing or two on the team as a whole.
- [ ] Instead of having a default layout for the team section, you could do a test for the `layout` of the `{{ range .Pages }}` you iterate over, so that any arbitrary text section anywhere could have a `team` layout and consequently be rendered as a team section. (Perhaps there is even a more 'native' way of doing this, but I couldn't so quickly find one.) This would fix the above issue but is not absolutely necessary.
- [ ] On the landing page, the really nice looking transparent menu doesn't make sense if and when more content is added to the page, which in the near future we might. Fixing this now is not absolutely necessary.

**Comment by ribeirojose** [comment]
So here is where it are now. 

> * [ ]  Proper indentation in templates, for (future) readability.

Done. This was caused by my linter, I am sorry. 

> * [ ]  Textual content is now rendered within a `<small>` within an `<h4>`!? Learn about [semantic HTML](https://www.lifewire.com/why-use-semantic-html-3468271) and apply it. No dirty hacks on this, it'll mess with our SEO. Although you don't have to do [this far](https://www.hongkiat.com/blog/html-5-semantics/), for now.

Ops, hadn't noticed this. Already fixed. 

> * [ ]  Newsletter button in menu bar doesn't have hover and link-type mouse pointer.

Fixed. 

> * [ ]  Pages always display a vertical scroll bar.

I could replicate this. Anyway, I have changed a CSS class that might be causing that.

> * [ ]  Social icon links on team page are not circles, they should be exactly as in the Now UI landing page.

Also wasn't aware that this was a requirement, but already fixed :-)

> * [ ]  Index page has different layouts that display differently.

I am not sure I understand what you mean by this. 

> * [ ]  The team page doesn't allow textual content. Of course, if we're introducing the members of the team, we would like to say a thing or two on the team as a whole.

Team page was a plus, but this is now fixed. =) 

> * [ ]  Instead of having a default layout for the team section, you could do a test for the `layout` of the `{{ range .Pages }}` you iterate over, so that any arbitrary text section anywhere could have a `team` layout and consequently be rendered as a team section. (Perhaps there is even a more 'native' way of doing this, but I couldn't so quickly find one.) This would fix the above issue but is not absolutely necessary.

I solved this using another strategy. 

> * [ ]  On the landing page, the really nice looking transparent menu doesn't make sense if and when more content is added to the page, which in the near future we might. That is, the previous behaviour really made a lot of sense (on that page). Fixing this now is not absolutely necessary.

I also failed to understand what you mean by this. Do you intend to append more headless pages to your landing page? I understand that works on the landing page were not agreed upon. We could, of course, agree to work on this as a next step. 

> One last hint, for the future: make as many small, independent, pull requests as possible, so you can hit a lot of milestones fast - instead of having huge atomic updates.

You are right!  This is our first time working with Hugo, so it was tricky to understand how fast we would get to hit our pre-defined requirements. Anyway, this is a big lesson learned =)

**Pull request merged**
